name: Copy build dir to Backend repo

on:
  push:
    branches:
      - master
    paths:
      - 'build/**'
  workflow_dispatch:


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (js)
        uses: actions/checkout@v2
        with:
          repository: 'spmaxsp/cocktailcloud-js'
          path: 'cocktailcloud-js'

      - name: Checkout destination (api)
        uses: actions/checkout@v2
        with:
          repository: 'spmaxsp/cocktailcloud-api'
          path: 'cocktailcloud-api'

      - name: Copy build dir to Backend repo
        run: |
          mkdir -p cocktailcloud-api/react-app/build
          rsync -av --progress cocktailcloud-js/build/* cocktailcloud-api/react-app/build
          ls -l cocktailcloud-api/react-app/build
          ls -l cocktailcloud-api
          ls -l

      - name: Commit changes
        run: |
          cd cocktailcloud-api
          touch test.txt
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit -m "Copy build dir from cocktailcloud-js repo"
          git push
          

