name: Copy build dir to Backend repo

on:
  push:
    branches:
      - master
    paths:
      - 'build/**'
  workflow_dispatch:


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (js)
        uses: actions/checkout@v2
        with:
          repository: 'spmaxsp/cocktailcloud-api'
          path: 'Backend'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout destination (api)
        uses: actions/checkout@v2
        with:
          repository: 'spmaxsp/cocktailcloud-api'
          path: 'Backend'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy build dir to Backend repo
        run: |
          mkdir -p react-app/build
          rsync -av --progress react-app/build/ Backend/build/

      - name: Commit changes
        run: |
          cd Backend
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Copy build dir from cocktailcloud-js repo"
          git push
          

